### ISSUE TITLE
Fastest 60 FPS is actually unlimited/uncapped FPS

### ISSUE THREAD

**Issue by veermaharaj** [CnCNet/cncnet-yr-client-package#171] opened 2022-09-30 06:42 UTC
Fastest 60 FPS is actually unlimited/uncapped FPS.

Previously under game speed there was an "unlimited option" where the game would run at a superfast uncapped speed. That option is gone and 60 fps is the highest/fastest option, however the game runs faster than 60 fps. It looks like its running uncapped.

Currently im playing at 45fps which is okay, but is notably slower than 60. So im guessing the 45fps option is running as it should.
60fps is broken.

**Comment by devo1929** [comment] 2022-09-30 10:18
This is a duplicate of https://github.com/CnCNet/cncnet-yr-client-package/issues/126

**Closed by devo1929** 2022-09-30 10:18 UTC
Labels: duplicate
